package com.example.thundora.model.utils

object CountryHelper {
    private val countryMap: Map<String, String> = mapOf(
        "AF" to "Afghanistan",
        "AL" to "Albania",
        "DZ" to "Algeria",
        "AD" to "Andorra",
        "AO" to "Angola",
        "AR" to "Argentina",
        "AM" to "Armenia",
        "AU" to "Australia",
        "AT" to "Austria",
        "AZ" to "Azerbaijan",
        "BH" to "Bahrain",
        "BD" to "Bangladesh",
        "BY" to "Belarus",
        "BE" to "Belgium",
        "BZ" to "Belize",
        "BJ" to "Benin",
        "BO" to "Bolivia",
        "BA" to "Bosnia and Herzegovina",
        "BR" to "Brazil",
        "BG" to "Bulgaria",
        "CA" to "Canada",
        "CL" to "Chile",
        "CN" to "China",
        "CO" to "Colombia",
        "HR" to "Croatia",
        "CU" to "Cuba",
        "CY" to "Cyprus",
        "CZ" to "Czech Republic",
        "DK" to "Denmark",
        "EG" to "Egypt",
        "FI" to "Finland",
        "FR" to "France",
        "DE" to "Germany",
        "GR" to "Greece",
        "IN" to "India",
        "ID" to "Indonesia",
        "IR" to "Iran",
        "IQ" to "Iraq",
        "IE" to "Ireland",
        "IT" to "Italy",
        "JP" to "Japan",
        "JO" to "Jordan",
        "KZ" to "Kazakhstan",
        "KE" to "Kenya",
        "KW" to "Kuwait",
        "LB" to "Lebanon",
        "LY" to "Libya",
        "MY" to "Malaysia",
        "MX" to "Mexico",
        "MA" to "Morocco",
        "NL" to "Netherlands",
        "NZ" to "New Zealand",
        "NG" to "Nigeria",
        "NO" to "Norway",
        "OM" to "Oman",
        "PK" to "Pakistan",
        "PS" to "Palestine",
        "PE" to "Peru",
        "PH" to "Philippines",
        "PL" to "Poland",
        "PT" to "Portugal",
        "QA" to "Qatar",
        "RO" to "Romania",
        "RU" to "Russia",
        "SA" to "Saudi Arabia",
        "RS" to "Serbia",
        "SG" to "Singapore",
        "ZA" to "South Africa",
        "KR" to "South Korea",
        "ES" to "Spain",
        "SE" to "Sweden",
        "CH" to "Switzerland",
        "SY" to "Syria",
        "TH" to "Thailand",
        "TN" to "Tunisia",
        "TR" to "Turkey",
        "UA" to "Ukraine",
        "AE" to "United Arab Emirates",
        "GB" to "United Kingdom",
        "US" to "United States",
        "UZ" to "Uzbekistan",
        "VE" to "Venezuela",
        "VN" to "Vietnam",
        "YE" to "Yemen",
        "ZW" to "Zimbabwe"
    )


    fun getCountryName(countryCode: String): String {
        return countryMap[countryCode] ?: countryCode
    }
}
